upstream dotnet_kestrel_http {
    # server api:5282;   # Kestrel 提供 HTTPS 的埠
    # server hr_leave_management_api:5282;
    server 172.95.15.31:5282;
}

server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    location / {
        # return 301 https://$host$request_uri;
        return 308 https://$host$request_uri;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html { root /usr/share/nginx/html; }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name localhost;

    ssl_certificate     /etc/nginx/ssl/HR.LeaveManagement.Clean.crt;
    ssl_certificate_key /etc/nginx/ssl/HR.LeaveManagement.Clean.key;

    #（其餘 SSL 設定留用）
    ssl_dhparam /etc/nginx/ssl/dhparam-2048.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        root /usr/share/nginx/html;
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
    }

    location /api {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '$http_origin' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,X-Requested-With' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        proxy_pass http://dotnet_kestrel_http;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 200m;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass_request_headers on;
    }

    # location /Images {
    #     alias /deploy/api/Images/;
    #     autoindex on;
    # }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html { root /usr/share/nginx/html; }
}
